### PR TITLE
Polars backend for Augment fourier

### PR DESCRIPTION
**Pull request by GTimothee**
Solves one task from #77 

Finally I found a workaround not to update ts_summary with polars for now, as it was not that trivial to do. I will try to do it next. But I wanted to separate both tasks.

Normally it should work as expected. I also added some tests.

### CODE REVIEW

**Comment by GTimothee** [comment]
I will try to see if I can improve the speed of the cal_fourier function. I think we can do better

**Comment by GTimothee** [comment]
I think I found a way to speedup the calc_fourier. I removed the three for loops and I compute 2 * np.pi * term * x only once with a numpy matrix multiplication. With 2 orders and 2 periods, it reduces the computation time from 2.3 ms to 1.38 ms according to my experiments. I will package it and push it later today :)

**Comment by mdancho84** [comment]
Excellent!

**Comment by mdancho84** [comment]
Hey, I wanted to get the preliminary merge complete. I noticed there were a few merge conflicts since @JustinKurland did some work on reducing memory usage.

**Comment by GTimothee** [comment]
Great, sorry I did not have much time I will do my best to deliver faster

**Pull request merged**
