### PR TITLE
Ts summary - polars backend

### PR DESCRIPTION
**Pull request by GTimothee**
partially solves #77 

Done, tests working. Updated augment_fourier so that it uses this new version.

Part of it depends on the function "get_frequency_summary" so it is the next on my list :) In the meantime I computed this part like this: `frequency_summary = pl.from_pandas(get_frequency_summary(date.to_pandas()))`

### CODE REVIEW

**Comment by mdancho84** [comment]
I'm seeing some failed tests on older versions of pandas. https://github.com/business-science/pytimetk/actions/runs/6739223865/job/18320315245?pr=211

image

image

**Comment by GTimothee** [comment]
Oh I see ! I will have a look

**Comment by mdancho84** [comment]
Ok, thanks. Let me know what you find out.

**Comment by GTimothee** [comment]
Apparently 2 different errors:
- pandas==2.0.0 : dtype error (not reproduced locally with python3.11, need to investigate further)
- pandas==1.5.0 : bug in the 1.5.0 version it seems. It has been fixed later on but maybe for this version to work I could think of a workaround (bug reference: https://github.com/pandas-dev/pandas/issues/45725)

**Comment by mdancho84** [comment]
Nice work! 1 test to go. Looks like datetime[ns] vs datetime[us]

**Comment by GTimothee** [comment]
yay 🎉

**Comment by mdancho84** [comment]
Nice work!

**Pull request merged**
